version: '3'
# cmd: docker-compose build & docker-compose up (build & run docker)
services:
  db:
    image: mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_USER=newroot
      - MYSQL_PASSWORD=528491
      - MYSQL_ROOT_PASSWORD=528491
      - MYSQL_DATABASE=xamreg

  api:
      image: xamreg/api
      build: api # setting build to ./api because Dockerfile is inside the api folder.
      container_name: api
      environment:
        - QUIZ_ENV=production
      volumes:
        - ./:/run
      restart: always
