version: '3'
# cmd: docker-compose build & docker-compose up (build & run docker)
services:
  db:
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=528491
    ports:
      - "5432:5432"
# mysql db
#    image: mysql:5.7
#    volumes:
#      - ./mysql-data:/var/lib/mysql
#    restart: always
#    environment:
#      - MYSQL_USER=newroot
#      - MYSQL_PASSWORD=528491
#      - MYSQL_ROOT_PASSWORD=528491
#      - MYSQL_DATABASE=xamreg

# postgres


#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    restart: always
#    depends_on:
#      - db
#    environment:
#      - PMA_HOST=db
#      - MYSQL_ROOT_PASSWORD=root
#    ports:
#      - 8090:80

  api:
    image: xamreg/api
    build: api # setting build to ./api because Dockerfile is inside the api folder.
    container_name: "flask_api_container"
    command: uwsgi --ini uwsgi.ini
    environment:
      - QUIZ_ENV=production
    volumes:
      - ./:/run
    restart: always
    depends_on:
      - db

  client:
    image: xamreg/client
    container_name: "vue_client_container"
    build: client
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always

  nginx:
    build: client/nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api