version: '3'
# cmd: docker-compose build & docker-compose up (build & run docker)
services:
  db:
    image: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_USER=newroot
      - MYSQL_PASSWORD=528491
      - MYSQL_ROOT_PASSWORD=528491
      - MYSQL_DATABASE=xamreg
    ports:
      - "3307:3307"

  api:
    command: python run.py
    environment:
      - QUIZ_ENV=development
    volumes:
      - ./:/run
    depends_on:
      - db
    ports:
      - "5000:5000"

  client:
    image: xamreg/client
    build: client
    container_name: client
    command: npm run dev
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always