version: '3'
# cmd: docker-compose build & docker-compose up (build & run docker)
services:
  db:
    image: mysql:5.7
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_USER=newroot
      - MYSQL_PASSWORD=528491
      - MYSQL_ROOT_PASSWORD=528491
      - MYSQL_DATABASE=xamreg

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      depends_on:
        - db
      environment:
        - PMA_HOST=db
        - MYSQL_ROOT_PASSWORD=root
      ports:
        - 8070:80

  api:
      command: python run.py
      environment:
        - QUIZ_ENV=development
      volumes:
        - ./:/run
      depends_on:
        - db
      ports:
        - "5000:5000"

  client:
    image: xamreg/client
    build: client
    container_name: client
    command: npm run dev
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always